/'
アクターの列挙
・購入者
・管理者

アクター毎のユースケースを列挙する
「〇〇が××する」
購入者が探す
購入者が見る
購入者が買う
管理者が登録する
管理者が発送する

対象に収める
ユースケースを整理する
'/
@startuml

actor 購入者
actor 管理者
left to right direction
rectangle ECシステム{
購入者 -right-> (商品を探す)
購入者 -right-> (商品を見る)
購入者 -right-> (商品を買う)

管理者 -left-> (商品を探す)
管理者 -left-> (商品を見る)
管理者 -left-> (商品を買う)
管理者 -left-> (商品を登録する)
管理者 -left-> (商品を発送する)

}

@enduml


